### ISSUE TITLE
Connecting Multiple Peripherals

### ISSUE THREAD

**Issue by iamterryclark** [jasminnisic/BITalinoBLE-Mac#2]
Hi Jasmin,

Firstly, thank you for creating this program!

I wondered how you might connect to multiple peripherals using this code base?

Also is this reading the packets as described in the MCU Datasheet from bitalino?

Best

Terry

**Comment by jasminnisic** [comment]
1. Connecting multiple peripherals should be possible with multiple BITalinoBLE instances.

2. Yes, it reads data as described in MCU Datasheet from BITalino.
